name: build-docker
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate docker-compose.yml
        run: docker compose config

      - name: Build backend & frontend
        run: docker compose build
